version: "3"
services:
 app:
   container_name: docker-node-mongo
   restart: always
   build: .
   env_file:
    - ./dev-config.env  
   ports:
    - "3000:3030"
   depends_on:
    - mongo

 mongo:
   container_name: mongo
   image: mongo
   ports:
     - "27017:27017"
   restart: always
   volumes:
     - /data:/data/db:Z
   
